# application.yml
server:
    port: 8181
spring:
  application:
    name: config-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true  # Enable service discovery
        service-name: config-service  # Optional: Custom service name
        register: true
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
#        :${server.port}
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    #    org:
    #      org.springframework.data.mongodb.core: debug
    #      hibernate: debug
    #      springframework:
    #        cache: debug
    org.springframework.cloud.consul: DEBUG







