server:
  port: 8484
spring:
  application:
    name: gateway-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true  # Enable service discovery
        service-name: gateway-service  # Optional: Custom service name
        register: true
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
  #        :${server.port}
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service  # Assuming BOOK-SERVICE is the service ID registered in your service discovery
          predicates:
            - Path=/books/**

        - id: book-service
          uri: lb://book-service  # Assuming BOOK-SERVICE is the service ID registered in your service discovery
          predicates:
            - Path=/image/**

        - id: book-audit-service
          uri: lb://book-audit # Replace with the correct service ID
          predicates:
            - Method=POST
            - Path=/audit/{bookName}
          filters:
            - RewritePath=/audit/(?<name>.*), /$\{name}

        - id: book-audit
          uri: lb://book-audit
          predicates:
            - Path=/audit/**
#
#        - id: book-audit
#          uri: lb://book-audit
#          predicates:
#            - Path=/audit/**
#          filters:
#            - RewritePath=/audit/(?<segment>.*), /$\{segment}

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.data.mongodb.core: debug
    hibernate: debug
    springframework.cache: debug
    org.springframework.cloud.consul: DEBUG
    org.springframework.cloud.gateway: DEBUG