# application.yml
server:
  port: 8383
spring:
  application:
    name: book-audit
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true  # Enable service discovery
        service-name: book-audit  # Optional: Custom service name
        register: true
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}
  #        :${server.port}
  data:
    mongodb:
      uri: mongodb://localhost:27017/books_audit
      username: mongodb
      password: mongodb
      profiles:
        active: dev
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.data.mongodb.core: debug
    org.springframework.cloud.consul: DEBUG







